-- =====================================================================
-- 0054_workflow_states_and_signals.sql
--   M6.0 — Asyncio orchestration substrate state + signal tables.
-- =====================================================================
-- Two tables every M6 asyncio service uses to satisfy the pattern-
-- alignment requirements from
-- [docs/ingestion/04-implementation-plan.md §M6](../../docs/ingestion/04-implementation-plan.md):
--
--   1. `workflow_states` — one row per (workflow_kind, workflow_id).
--      Carries the orchestration state as JSONB plus the
--      load-bearing `last_advanced_at` timestamp that the N1
--      cursor-data ordering invariant (LLD §3.1) updates only AFTER
--      a successful Kafka publish + broker-ack flush.
--
--      Pattern-alignment mapping (Rule 2: state-in-Postgres-not-memory):
--      Every progress-bearing variable for an M6 service lives in
--      `state_data`. The asyncio process holds NO state that wouldn't
--      survive a SIGTERM-restart. Recovery on startup is `load_state(
--      workflow_kind, workflow_id)` — no in-memory caches to warm,
--      no per-process counters to reconcile.
--
--   2. `workflow_signals` — append-only signal table for cross-service
--      Postgres-polling communication.
--
--      Pattern-alignment mapping (Rule 4: signals-via-Postgres-polling):
--      Cross-service handoffs go through this table, not via
--      `asyncio.Queue` or shared globals. A producer service INSERTs;
--      a consumer service polls with `FOR UPDATE SKIP LOCKED` and
--      stamps `consumed_at`. Maps 1:1 to Temporal's `signal_workflow`
--      API when the [A11 trigger conditions](../../docs/ingestion/05-lld-amendments.md)
--      fire — same shape, different transport.
--
-- Same persistence rationale as 0052 (M3.3) + 0053 (M5.1):
--   Path A services already hold an asyncpg pool. Putting orchestration
--   state in Postgres rather than Redis keeps durability in one place;
--   a Redis restart cannot split the state (counter says "advanced"
--   but cursor row disagrees) the way it could if state spanned two
--   stores.
--
-- Idempotency contract:
--   `workflow_signals.idempotency_key` is NOT NULL by design. Callers
--   that need dedup pass a stable key (e.g.
--   `f"feels_onboarded:{tenant}:{source}"`); callers that don't want
--   dedup pass a fresh `uuid7().hex` per emit. The NOT NULL constraint
--   makes the contract explicit: every signal has an idempotency
--   identity. A NULL-permitting design would let `emit_signal(...)`
--   silently fall into "two emits with no key both succeed" — which
--   is exactly the surprising behaviour we want the schema to
--   prevent.
--
-- Constitution alignment:
--   §I — bounded to M6.0 substrate.
--   §II — additive; idempotent CREATE.
--   §III — RLS deferred: workflow services run as privileged operator
--          roles. tenant_id IS nullable on workflow_states (some
--          workflows are global, e.g. FeelsOnboardedMonitor scans
--          all tenants); when present it carries an FK to tenants
--          for integrity.
-- =====================================================================

BEGIN;

-- ---------------------------------------------------------------------
-- workflow_states
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS workflow_states (
    workflow_kind       TEXT         NOT NULL,
    workflow_id         TEXT         NOT NULL,
    -- NULLABLE: tenant-scoped workflows populate this; global workflows
    -- (e.g. the FeelsOnboardedMonitor that scans all tenants) leave it
    -- NULL. The FK keeps tenant-scoped rows referentially honest.
    tenant_id           UUID         REFERENCES tenants(id),
    state_data          JSONB        NOT NULL DEFAULT '{}'::jsonb,
    -- Updated ONLY by `advance_cursor_atomic_with_kafka_publish` after
    -- a successful broker-ack flush (the N1 invariant; LLD §3.1).
    last_advanced_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    -- NULLABLE: set by an operator to halt this workflow's progression
    -- without deleting state. The asyncio service checks `paused_at IS
    -- NOT NULL` and skips advancement when paused.
    paused_at           TIMESTAMPTZ,
    PRIMARY KEY (workflow_kind, workflow_id)
);

-- Diagnostic index: find recently-advanced workflows of a given kind.
-- Useful for "is the FeelsOnboardedMonitor making progress?" operator
-- queries.
CREATE INDEX IF NOT EXISTS workflow_states_kind_advanced_idx
    ON workflow_states (workflow_kind, last_advanced_at DESC);

-- ---------------------------------------------------------------------
-- workflow_signals
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS workflow_signals (
    -- uuid7 generated by the caller (`lib.shared.ids.uuid7`).
    -- We require it as PK rather than auto-generating so the caller
    -- has the id BEFORE the insert (idempotent INSERT retries can
    -- reference it; tests can predict it).
    id                  UUID         PRIMARY KEY,
    workflow_kind       TEXT         NOT NULL,
    workflow_id         TEXT         NOT NULL,
    signal_kind         TEXT         NOT NULL,
    signal_data         JSONB        NOT NULL DEFAULT '{}'::jsonb,
    -- NOT NULL by design — see header comment on idempotency contract.
    idempotency_key     TEXT         NOT NULL,
    created_at          TIMESTAMPTZ  NOT NULL DEFAULT now(),
    -- NULL = unclaimed. Set to now() when a poller claims via
    -- `SELECT ... FOR UPDATE SKIP LOCKED ... UPDATE consumed_at`.
    consumed_at         TIMESTAMPTZ,
    -- Audit: which service instance claimed this signal.
    consumed_by         TEXT,
    -- The dedup invariant: a producer emitting the same logical signal
    -- twice (same key) collides on this constraint and the second
    -- INSERT no-ops via ON CONFLICT DO NOTHING. This is what
    -- `emit_signal(...)` relies on for idempotent emit across retries.
    UNIQUE (workflow_kind, workflow_id, signal_kind, idempotency_key)
);

-- Polling-side hot path: "give me unclaimed signals for this workflow,
-- oldest first." Partial index on `consumed_at IS NULL` is small
-- because consumed signals dominate over time. Postgres 15+
-- NULLS DISTINCT default makes the partial-index semantics natural
-- (same pattern as M3.1's migration 0051).
CREATE INDEX IF NOT EXISTS workflow_signals_unclaimed_idx
    ON workflow_signals (workflow_kind, workflow_id, created_at)
    WHERE consumed_at IS NULL;

COMMIT;
