"""
services/retrieval/maintenance.py — background relationship
maintenance (spec §10 / BUILD-PLAN §4 Prompt 3.A item 5).

Runs nightly (Wave 4-D schedules). Primitives:

  - background_relationship_maintenance(tenant_id, conn) -> MaintenanceReport

Flow:
  1. Walk `supporting_model_ids` graph for active Models.
     Any active Model whose every entry in supporting_model_ids is
     archived is an "orphan" — cascade-archival candidate. Flag to the
     log (DO NOT archive here; Precipitation worker 4-C acts on the
     flags).
  2. Compute activation percentiles (p10 / p50 / p90) for active
     Models grouped by proposition_kind. Flag outliers (> p90 × 2)
     for Anomaly processor attention — again, only a flag.
  3. Suggest archivals: Models with activation < 0.05 AND
     last_retrieved_at < now()-30d (or NULL) AND status='active'.
     Report (do not archive).
  4. Every decision emits a row into `relationship_maintenance_log`.
     The only write side-effect.

Invariants:
  - Does NOT mutate `models` (reconsolidation is a retrieval pathway,
    not this worker).
  - Does NOT enqueue any queue (no think_trigger_queue inserts, no
    model_reeval_queue inserts — it only *flags* via the log).
  - A single `run_id` groups every entry generated by one invocation.
  - Tenant-scoped: every query and every log row carries `tenant_id`.

Returns a `MaintenanceReport` (count snapshot). Truth lives in the
log table.
"""
from __future__ import annotations

import json
import statistics
from dataclasses import dataclass, field
from datetime import datetime, timedelta, timezone
from typing import Any
from uuid import UUID

import asyncpg

from lib.shared.errors import CompanyOSError
from lib.shared.ids import uuid7


# ---------------------------------------------------------------------
# Thresholds + constants
# ---------------------------------------------------------------------

_ARCHIVAL_ACTIVATION_THRESHOLD = 0.05
_ARCHIVAL_STALE_DAYS = 30
_OUTLIER_MULTIPLIER = 2.0
_MIN_POP_FOR_PERCENTILES = 3   # percentiles of <3 points are meaningless


# Entry kinds — must match the CHECK-friendly set described in migration
# 0006. Enforced application-side (no DB CHECK; keeps future-kind
# additions backward compatible).
_ENTRY_KIND_ORPHAN = "orphan_flagged"
_ENTRY_KIND_OUTLIER = "activation_outlier"
_ENTRY_KIND_ARCHIVAL = "archival_suggested"
_ENTRY_KIND_PERCENTILE = "percentile_snapshot"


class MaintenanceError(CompanyOSError):
    default_code = "maintenance_error"


@dataclass
class MaintenanceReport:
    """
    Counts-only snapshot of one maintenance invocation. Truth for each
    flagged entity lives in `relationship_maintenance_log`.
    """

    tenant_id: UUID
    run_id: UUID
    run_started_at: datetime
    orphans_flagged: int = 0
    activation_outliers: int = 0
    archival_suggestions: int = 0
    percentile_snapshots: int = 0
    active_models_scanned: int = 0
    notes: dict[str, Any] = field(default_factory=dict)


# ---------------------------------------------------------------------
# Internal — log insertion
# ---------------------------------------------------------------------


async def _log_entry(
    conn: asyncpg.Connection,
    *,
    tenant_id: UUID,
    run_id: UUID,
    run_started_at: datetime,
    entry_kind: str,
    subject_model_id: UUID | None,
    payload: dict[str, Any],
) -> None:
    await conn.execute(
        """
        INSERT INTO relationship_maintenance_log (
          id, tenant_id, run_id, run_started_at,
          entry_kind, subject_model_id, payload
        ) VALUES ($1, $2, $3, $4, $5, $6, $7::jsonb)
        """,
        uuid7(),
        tenant_id,
        run_id,
        run_started_at,
        entry_kind,
        subject_model_id,
        json.dumps(payload, sort_keys=True, default=str),
    )


# ---------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------


async def background_relationship_maintenance(
    tenant_id: UUID,
    conn: asyncpg.Connection,
    *,
    now: datetime | None = None,
    archival_stale_days: int = _ARCHIVAL_STALE_DAYS,
    archival_threshold: float = _ARCHIVAL_ACTIVATION_THRESHOLD,
    outlier_multiplier: float = _OUTLIER_MULTIPLIER,
) -> MaintenanceReport:
    """
    Execute one full maintenance pass for `tenant_id`. All queries run
    against the caller's `conn`; the caller may wrap this in a
    transaction (recommended so the log rows are atomic with any
    future flag consumers).

    Never mutates `models`. Only writes to
    `relationship_maintenance_log`.
    """
    now = now or datetime.now(timezone.utc)
    run_id = uuid7()
    run_started_at = now

    # -----------------------------------------------------------------
    # 0. Load active Models (minimal columns — we don't need full
    # ModelRow hydration for a maintenance pass).
    # -----------------------------------------------------------------
    active_rows = await conn.fetch(
        """
        SELECT id, proposition_kind, activation, last_retrieved_at,
               supporting_model_ids, status
        FROM models
        WHERE tenant_id = $1 AND status = 'active'
        """,
        tenant_id,
    )

    active_models = [dict(r) for r in active_rows]
    report = MaintenanceReport(
        tenant_id=tenant_id,
        run_id=run_id,
        run_started_at=run_started_at,
        active_models_scanned=len(active_models),
    )

    if not active_models:
        report.notes["reason"] = "no_active_models"
        return report

    # -----------------------------------------------------------------
    # 1. Orphan detection — every entry in supporting_model_ids archived.
    # -----------------------------------------------------------------
    all_supporting_ids: set[UUID] = set()
    for m in active_models:
        for smid in m["supporting_model_ids"] or []:
            all_supporting_ids.add(smid)
    archived_supporting: set[UUID] = set()
    if all_supporting_ids:
        archived_rows = await conn.fetch(
            """
            SELECT id FROM models
            WHERE id = ANY($1::uuid[])
              AND status IN ('archived', 'superseded', 'contested_false')
            """,
            list(all_supporting_ids),
        )
        archived_supporting = {r["id"] for r in archived_rows}

    for m in active_models:
        supporting = m["supporting_model_ids"] or []
        if not supporting:
            continue
        all_archived = all(smid in archived_supporting for smid in supporting)
        if not all_archived:
            continue
        await _log_entry(
            conn,
            tenant_id=tenant_id,
            run_id=run_id,
            run_started_at=run_started_at,
            entry_kind=_ENTRY_KIND_ORPHAN,
            subject_model_id=m["id"],
            payload={
                "supporting_model_ids": [str(x) for x in supporting],
                "all_supporting_archived": True,
            },
        )
        report.orphans_flagged += 1

    # -----------------------------------------------------------------
    # 2. Activation percentiles per proposition_kind + outlier flags.
    # -----------------------------------------------------------------
    by_kind: dict[str | None, list[float]] = {}
    by_kind_rows: dict[str | None, list[dict]] = {}
    for m in active_models:
        kind = m["proposition_kind"]
        by_kind.setdefault(kind, []).append(float(m["activation"]))
        by_kind_rows.setdefault(kind, []).append(m)

    for kind, vals in by_kind.items():
        if len(vals) < _MIN_POP_FOR_PERCENTILES:
            continue
        try:
            p10 = _percentile(vals, 10)
            p50 = _percentile(vals, 50)
            p90 = _percentile(vals, 90)
        except statistics.StatisticsError:
            continue
        await _log_entry(
            conn,
            tenant_id=tenant_id,
            run_id=run_id,
            run_started_at=run_started_at,
            entry_kind=_ENTRY_KIND_PERCENTILE,
            subject_model_id=None,
            payload={
                "proposition_kind": kind,
                "population": len(vals),
                "p10": p10,
                "p50": p50,
                "p90": p90,
            },
        )
        report.percentile_snapshots += 1
        threshold = p90 * outlier_multiplier
        for m in by_kind_rows[kind]:
            if float(m["activation"]) > threshold:
                await _log_entry(
                    conn,
                    tenant_id=tenant_id,
                    run_id=run_id,
                    run_started_at=run_started_at,
                    entry_kind=_ENTRY_KIND_OUTLIER,
                    subject_model_id=m["id"],
                    payload={
                        "activation": float(m["activation"]),
                        "p90": p90,
                        "threshold": threshold,
                        "proposition_kind": kind,
                    },
                )
                report.activation_outliers += 1

    # -----------------------------------------------------------------
    # 3. Archival suggestions.
    # -----------------------------------------------------------------
    cutoff = now - timedelta(days=archival_stale_days)
    for m in active_models:
        if float(m["activation"]) >= archival_threshold:
            continue
        last_ret = m["last_retrieved_at"]
        if last_ret is not None and last_ret >= cutoff:
            continue
        await _log_entry(
            conn,
            tenant_id=tenant_id,
            run_id=run_id,
            run_started_at=run_started_at,
            entry_kind=_ENTRY_KIND_ARCHIVAL,
            subject_model_id=m["id"],
            payload={
                "activation": float(m["activation"]),
                "last_retrieved_at": (
                    last_ret.isoformat() if last_ret else None
                ),
                "cutoff": cutoff.isoformat(),
                "reason": "low_activation_stale_retrieval",
            },
        )
        report.archival_suggestions += 1

    report.notes["percentile_kinds"] = sorted(
        k for k in by_kind if len(by_kind[k]) >= _MIN_POP_FOR_PERCENTILES
    )
    return report


# ---------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------


def _percentile(values: list[float], pct: int) -> float:
    """
    Linear interpolation between closest ranks. Matches numpy's
    default 'linear' interpolation. Empty list raises; len==1 returns
    the single value; else interpolates.
    """
    if not values:
        raise statistics.StatisticsError("percentile() requires non-empty list")
    s = sorted(values)
    if len(s) == 1:
        return float(s[0])
    k = (len(s) - 1) * (pct / 100.0)
    f = int(k)
    c = min(f + 1, len(s) - 1)
    if f == c:
        return float(s[f])
    return float(s[f] + (s[c] - s[f]) * (k - f))


__all__ = [
    "MaintenanceReport",
    "MaintenanceError",
    "background_relationship_maintenance",
]
