"""tests/integration/test_section7_full_scenarios.py

COMPANY-OS-UI-BUILD-PLAN §7 integration test battery — automation pass.

Covers:
  - Test 1 (full scenario replay, `acme_tuesday`) — payload shape.
  - Test 2 (quiet-day scenario, `quiet_week`) — quiet register assertions.
  - Test 3 (concurrent scenarios, `two_fires`) — >=2 hot cards.
  - Test 4 (query coverage, the 6 categories) — non-empty `response_html`
    returned for a representative query per category.
  - Test 5 (staleness behavior) — force cache cached_at to now-1h,
    assert `GET /view/ceo/home` returns `staleness_seconds > 3500`.

Tests 6 (WS reconnect) and 7 (voice consistency spot check) are
covered elsewhere: Test 6 is Playwright (`ui/e2e/ws-reconnect.spec.ts`);
Test 7 is a standalone smoke script at `scripts/voice_spot_check.py`.

Each scenario test drives a minimal force-refresh against the captured
fixture dump rather than requiring a live LLM + replayed scenario on
every CI run. The fixtures live in `tests/integration/captures/` and
are regenerated by `scripts/capture_scenario_home.py <scenario>`.

Running live (regenerate captures): follow the BUILD-LOG Week 6 runbook.
Running in CI: fixtures act as the source of truth; the tests pin the
shape + semantic invariants the UI depends on.
"""
from __future__ import annotations

import json
import os
from pathlib import Path
from typing import Any
from uuid import UUID

import pytest

ROOT = Path(__file__).resolve().parent.parent.parent
CAPTURES_DIR = ROOT / "tests" / "integration" / "captures"
DOGFOOD_TENANT = UUID("00000000-0000-7000-8000-000000000dd1")


# ---------------------------------------------------------------------
# Capture-backed assertions (always-on — no external deps beyond the
# captured JSON fixtures).
# ---------------------------------------------------------------------


def _load_capture(name: str) -> dict[str, Any]:
    path = CAPTURES_DIR / f"{name}_home.json"
    if not path.exists():
        pytest.skip(
            f"capture missing: {path.relative_to(ROOT)} — "
            "regenerate with scripts/capture_scenario_home.py"
        )
    return json.loads(path.read_text())


def _assert_home_shape(payload: dict[str, Any]) -> None:
    """CONTRACTS §1.1 shape invariants — applies to every scenario."""
    for key in ("greeting", "query_grid", "cards", "close_line", "status"):
        assert key in payload, f"missing {key!r}"

    g = payload["greeting"]
    assert "meta" in g
    assert isinstance(g["meta"].get("date_iso"), str) and g["meta"]["date_iso"]
    assert "body_html" in g and isinstance(g["body_html"], str)
    # Voice: no JSON-wrapped HTML leaking through (Week-5 fix guard).
    body = g["body_html"].lstrip()
    assert not body.startswith("{"), (
        "greeting body_html starts with '{' — DeepSeek JSON-wrap leak"
    )
    assert "staleness_seconds" in g
    assert isinstance(g["staleness_seconds"], (int, float))

    qg = payload["query_grid"]
    assert isinstance(qg["queries"], list)
    for q in qg["queries"]:
        assert {"id", "icon", "label", "hot"} <= q.keys(), q

    assert isinstance(payload["cards"], list)
    for c in payload["cards"]:
        assert {"id", "kind", "tag_color", "tag_label", "body_html"} <= c.keys(), c
        assert c["kind"] in ("observation", "decision", "question")
        assert c["tag_color"] in ("hot", "warm", "soft")
        assert isinstance(c["body_html"], str) and c["body_html"].strip()

    assert isinstance(payload["close_line"]["body"], str)
    assert payload["close_line"]["body"].strip()

    status = payload["status"]
    assert isinstance(status["substrate_alive"], bool)
    assert isinstance(status["calibration_pct"], (int, float))
    assert isinstance(status["needs_you_count"], int)


def test_section7_test1_acme_tuesday_home_shape() -> None:
    """§7 Test 1 (automatable part): `acme_tuesday` → GET /view/ceo/home
    returns the §1.1 shape, with non-empty greeting and cards."""
    payload = _load_capture("acme_tuesday")
    _assert_home_shape(payload)
    # On an active scenario we expect at least one hot card (the
    # observation) and the greeting to be longer than the quiet-day
    # minimum.
    hot_cards = [c for c in payload["cards"] if c["tag_color"] == "hot"]
    assert hot_cards, "acme_tuesday should produce at least one hot card"
    assert len(payload["greeting"]["body_html"]) >= 80


def test_section7_test2_quiet_week_quiet_register() -> None:
    """§7 Test 2: quiet-day replay → greeting is short, no hot cards,
    `signals_watched_count` small, the two-beat form holds.

    The voice register check is in `scripts/voice_spot_check.py`; here
    we assert the structural quiet-day invariants the design doc §8
    demands: no manufactured urgency, no hot cards."""
    payload = _load_capture("quiet_week")
    _assert_home_shape(payload)

    # Quiet register: greeting should collapse to two beats. We pin a
    # length ceiling; demonstrated quiet greeting in design doc §10.2
    # is 17 words / ~90 chars ("Good morning. Nothing consequential
    # since yesterday; the company is running at normal metabolism.").
    # We give ourselves a 2x headroom before flagging.
    body_html = payload["greeting"]["body_html"]
    assert len(body_html) <= 340, (
        f"quiet_week greeting is {len(body_html)} chars — too noisy. "
        f"Design doc §10.2 calls for a two-beat collapse.\n"
        f"Body: {body_html[:300]}"
    )

    # No hot-tagged cards on a quiet day.
    hot_cards = [c for c in payload["cards"] if c["tag_color"] == "hot"]
    assert not hot_cards, (
        f"quiet_week should have no hot cards; got {len(hot_cards)}: "
        f"{[c['id'] for c in hot_cards]}"
    )

    # No hot-tagged queries on a quiet day (CEO prompt grid is
    # evergreen-only per §10.3).
    hot_queries = [q for q in payload["query_grid"]["queries"] if q.get("hot")]
    assert not hot_queries, (
        f"quiet_week should have no hot queries; got {len(hot_queries)}"
    )


def test_section7_test3_two_fires_multiple_hot_cards() -> None:
    """§7 Test 3: concurrent-scenarios replay → at least two hot-tagged
    cards rank in the grid, and the greeting handles more than one
    situation without losing specificity."""
    payload = _load_capture("two_fires")
    _assert_home_shape(payload)

    hot_cards = [c for c in payload["cards"] if c["tag_color"] == "hot"]
    assert len(hot_cards) >= 2, (
        f"two_fires should produce >=2 hot cards; got {len(hot_cards)}: "
        f"{[c['id'] for c in hot_cards]}"
    )

    # Specificity: the greeting should name two distinct nouns. Rather
    # than a brittle word-match, we check overall greeting length meets
    # a floor (substantial prose) and that body_html is not empty.
    body_html = payload["greeting"]["body_html"]
    assert len(body_html) >= 120, (
        "two_fires greeting too short to cover two situations"
    )


# ---------------------------------------------------------------------
# §7 Test 4 — query coverage.
#
# Runs against the live gateway (needs DATABASE_URL + LLM provider) so
# the full classify → retrieve → render pipeline exercises. Skipped
# when the environment doesn't provide those.
# ---------------------------------------------------------------------


# One representative query per classifier.py::QueryCategory.
_QUERY_CATEGORY_SAMPLES: tuple[tuple[str, str], ...] = (
    ("why", "Why is Acme at risk?"),
    ("show_me", "Show me the open commitments this week."),
    ("draft", "Draft a brief for Monica."),
    ("what_if", "What if we extend the Acme renewal 30 days?"),
    ("summary", "What happened yesterday?"),
    ("arbitrary", "Where is the company silent where it shouldn't be?"),
)


pytestmark_query_coverage = pytest.mark.skipif(
    os.environ.get("SECTION7_QUERY_COVERAGE") != "1",
    reason="set SECTION7_QUERY_COVERAGE=1 to run (requires live LLM + scenario replayed)",
)


@pytest.fixture
async def gateway_app():
    """Build the gateway app with lifespan so all Week-4+ routers mount."""
    from services.gateway.main import build_app

    app = build_app()
    async with app.router.lifespan_context(app):
        yield app


@pytest.mark.asyncio
@pytestmark_query_coverage
@pytest.mark.parametrize("category,query", _QUERY_CATEGORY_SAMPLES)
async def test_section7_test4_query_coverage(
    gateway_app, category: str, query: str
) -> None:
    """§7 Test 4: each of the 6 classifier categories produces a
    non-empty, well-formed `response_html`."""
    import httpx

    transport = httpx.ASGITransport(app=gateway_app)
    async with httpx.AsyncClient(
        transport=transport, base_url="http://gateway", timeout=120
    ) as client:
        r = await client.post(
            "/view/ceo/ask",
            json={"query": query},
            headers={"x-tenant-id": str(DOGFOOD_TENANT)},
        )
    assert r.status_code == 200, r.text
    body = r.json()
    for key in (
        "turn_id", "query_echo", "response_html",
        "verbs", "computed_at", "latency_ms",
    ):
        assert key in body, f"[{category}] missing {key!r}"
    assert isinstance(body["response_html"], str)
    html = body["response_html"].strip()
    assert html, f"[{category}] empty response_html"
    assert not html.startswith("{"), (
        f"[{category}] JSON-wrap leak in response_html"
    )
    # Voice-rules-compliant HTML never contains exclamation marks.
    assert "!" not in html, f"[{category}] response_html contains !"


# ---------------------------------------------------------------------
# §7 Test 5 — staleness behavior.
#
# Forces a cache row's `cached_at` backward 1h, asserts /view/ceo/home
# reports `staleness_seconds > 3500`. Runs when DATABASE_URL is set.
# ---------------------------------------------------------------------


@pytest.mark.asyncio
@pytest.mark.integration
async def test_section7_test5_staleness_threshold(monkeypatch) -> None:
    if not os.environ.get("DATABASE_URL"):
        pytest.skip("DATABASE_URL unset — integration only")
    import asyncpg
    from services.gateway.main import build_app

    # Ensure the scheduler doesn't race us by overwriting the cached_at
    # we're about to backdate.
    monkeypatch.setenv("GATEWAY_START_GRT_SCHEDULER", "0")
    # Ensure the dogfood tenant id is set so the default tenant is
    # registered.
    monkeypatch.setenv(
        "DEFAULT_TENANT_ID", str(DOGFOOD_TENANT)
    )

    app = build_app()
    async with app.router.lifespan_context(app):
        dsn = os.environ["DATABASE_URL"]
        # Seed a minimal cache row if missing, then backdate it.
        async with asyncpg.create_pool(dsn, min_size=1, max_size=2) as pool:
            async with pool.acquire() as conn:
                row = await conn.fetchrow(
                    """
                    SELECT cache_key FROM view_ceo_cache
                    WHERE tenant_id = $1 AND cache_key = 'greeting'
                    """,
                    DOGFOOD_TENANT,
                )
                if row is None:
                    # Seed a tiny placeholder greeting so the endpoint
                    # has something to read.
                    await conn.execute(
                        """
                        INSERT INTO view_ceo_cache
                            (tenant_id, cache_key, cached_content, cached_at)
                        VALUES ($1, 'greeting', $2, now())
                        ON CONFLICT (tenant_id, cache_key) DO UPDATE
                            SET cached_content = EXCLUDED.cached_content,
                                cached_at = now()
                        """,
                        DOGFOOD_TENANT,
                        json.dumps({
                            "meta": {
                                "date_iso": "2026-04-22",
                                "recomputed_at": "2026-04-22T00:00:00Z",
                                "signals_watched_count": 0,
                            },
                            "body_html": "Good morning.",
                            "cached_at": "2026-04-22T00:00:00Z",
                        }),
                    )
                # Backdate.
                await conn.execute(
                    """
                    UPDATE view_ceo_cache
                    SET cached_at = now() - interval '1 hour'
                    WHERE tenant_id = $1 AND cache_key = 'greeting'
                    """,
                    DOGFOOD_TENANT,
                )

        import httpx

        transport = httpx.ASGITransport(app=app)
        async with httpx.AsyncClient(
            transport=transport, base_url="http://gateway"
        ) as client:
            r = await client.get("/view/ceo/home")
        assert r.status_code == 200, r.text
        body = r.json()
        staleness = body["greeting"]["staleness_seconds"]
        assert staleness > 3500, (
            f"expected staleness_seconds > 3500 after 1h backdate, "
            f"got {staleness!r}"
        )
