#!/usr/bin/env python3
"""Generate docker-compose.per-source.yml — the per-source-isolated
ingestion worker topology.

Per docs/ingestion/source-isolation.md. The base `docker-compose.yml`
runs ONE all-sources worker per data-plane stage (INGESTION_SOURCE unset
-> the worker subscribes to every per-source topic). That is the right
shape for a single-box dogfood.

For true source isolation you want one worker PROCESS per (source, stage)
so lag/failure/backpressure in one source cannot touch another, and each
source can be scaled independently. docker-compose has no loop construct,
so we generate the file from the source registry instead of hand-writing
8 sources x 3 stages = 24 services (and re-generate when a source is
added). Run:

    python scripts/gen_per_source_compose.py > docker-compose.per-source.yml

Use it WITH the base file, having scaled the all-sources singletons to 0:

    docker compose -f docker-compose.yml -f docker-compose.per-source.yml \
        up -d --scale normalizer=0 --scale observation_writer=0 \
        --scale embedding_worker=0

The dlq_writer stays all-sources (DLQ is low-volume by design), so it is
NOT split here.

The generated services are fully specified (no cross-file YAML anchors)
because anchors are file-scoped; `depends_on` names resolve against the
base file when both are passed to `docker compose`.
"""
from __future__ import annotations

import sys

from services.ingestion.kafka.topics import INGESTION_SOURCES

# (stage-label, module path, base consumer-group). One worker per source
# per stage. dlq_writer intentionally omitted (stays all-sources).
_STAGES = (
    ("normalizer", "services.ingestion.normalizer.worker"),
    ("observation-writer", "services.ingestion.writers.observation_writer"),
    (
        "embedding-worker",
        "services.ingestion.writers.embedding_worker.embedding_worker",
    ),
)

_HEADER = """\
# GENERATED by scripts/gen_per_source_compose.py — DO NOT EDIT BY HAND.
# Per-source-isolated ingestion worker topology (source-isolation).
# Re-generate after changing RawEnvelope.SourceLiteral:
#   python scripts/gen_per_source_compose.py > docker-compose.per-source.yml
#
# Use WITH the base file, all-sources singletons scaled to 0:
#   docker compose -f docker-compose.yml -f docker-compose.per-source.yml \\
#       up -d --scale normalizer=0 --scale observation_writer=0 \\
#       --scale embedding_worker=0
"""

# Health port is per-container localhost (not host-published), so every
# worker can keep 9300 without colliding.
_SERVICE_TMPL = """\
  {svc_name}:
    build: .
    restart: unless-stopped
    depends_on:
      postgres: {{condition: service_healthy}}
      kafka: {{condition: service_healthy}}
      minio: {{condition: service_healthy}}
      redis: {{condition: service_healthy}}
      migrate: {{condition: service_completed_successfully}}
      kafka-init: {{condition: service_completed_successfully}}
      minio-init: {{condition: service_completed_successfully}}
    environment:
      DATABASE_URL: postgresql://company_os:company_os@postgres:5432/company_os
      OLLAMA_URL: http://ollama:11434
      COMPANY_OS_ENV: prod
      FYRALIS_ENV: prod
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      S3_ENDPOINT_URL: http://minio:9000
      S3_RAW_BUCKET: fyralis-raw
      S3_REGION_NAME: us-east-1
      AWS_ACCESS_KEY_ID: fyralis
      AWS_SECRET_ACCESS_KEY: fyralis-secret-change-me
      REDIS_URL: redis://redis:6379/0
      INGESTION_HEALTH_PORT: "9300"
      # Source isolation: pin this worker to one source's lane.
      INGESTION_SOURCE: {source}
    env_file: .env.production
    container_name: company_os_{stage_us}_{source}
    command: python -m {module}
    healthcheck:
      test: ["CMD-SHELL", "python -c \\"import urllib.request,sys; sys.exit(0 if urllib.request.urlopen('http://localhost:9300/healthz').status==200 else 1)\\""]
      interval: 15s
      timeout: 5s
      retries: 4
      start_period: 30s
"""


def render() -> str:
    out = [_HEADER, "", "services:"]
    for stage_label, module in _STAGES:
        stage_us = stage_label.replace("-", "_")
        out.append(f"  # ---- {stage_label} (per source) ----")
        for source in INGESTION_SOURCES:
            out.append(
                _SERVICE_TMPL.format(
                    svc_name=f"{stage_us}_{source}",
                    stage_us=stage_us,
                    source=source,
                    module=module,
                ).rstrip("\n")
            )
            out.append("")
    return "\n".join(out) + "\n"


def main() -> int:
    sys.stdout.write(render())
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
