{{- if .Values.redis.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "fyralis.redisName" . }}
  labels:
    {{- include "fyralis.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  ports:
    - name: redis
      port: 6379
      targetPort: redis
  selector:
    {{- include "fyralis.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: redis
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fyralis.redisName" . }}
  labels:
    {{- include "fyralis.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "fyralis.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: redis
  template:
    metadata:
      labels:
        {{- include "fyralis.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: redis
    spec:
      containers:
        - name: redis
          image: {{ .Values.redis.image }}
          imagePullPolicy: IfNotPresent
          args:
            - redis-server
            - --save
            - ""
            - --appendonly
            - "no"
          ports:
            - name: redis
              containerPort: 6379
{{- end }}
