apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fyralis.appSecretName" . }}
  labels:
    {{- include "fyralis.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_PASSWORD: {{ .Values.postgres.password | quote }}
  DATABASE_URL: {{ printf "postgresql://%s:%s@%s:5432/%s" .Values.postgres.user .Values.postgres.password (include "fyralis.postgresName" .) .Values.postgres.database | quote }}
  MINIO_ROOT_PASSWORD: {{ .Values.minio.rootPassword | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.minio.rootPassword | quote }}
  AUTH_BOOTSTRAP_SECRET: {{ .Values.app.authBootstrapSecret | quote }}
  MASTER_KEK: {{ .Values.app.masterKek | quote }}
