/** @type {import('tailwindcss').Config} */
// Fyralis — design tokens mirror FYRALIS_TODAY_SPEC.md §2.
// CSS variables are the source of truth (declared in src/index.css).
// Tailwind tokens here exist so utility classes resolve to the same palette.
export default {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        base: "#F4F5F7",
        "base-recess": "#E9EBEF",
        "base-deep": "#DCDFE5",
        surface: "#FFFFFF",
        "surface-soft": "#F9FAFB",
        ink: "#0A0A0F",
        "ink-2": "#2C2D33",
        "ink-3": "#5A5C66",
        "ink-4": "#8B8D96",
        "ink-5": "#C5C7D0",
        rule: "#C5C7D0",
        "rule-soft": "#E1E3E9",
        "rule-faint": "#ECEEF2",
        accent: "#0F766E",
        "accent-hover": "#115E59",
        "accent-deep": "#134E4A",
        "accent-soft": "#99F6E4",
        "accent-faint": "#CCFBF1",
        critical: "#991B1B",
        "critical-bg": "#FEE2E2",
        "critical-bg-2": "#FCA5A5",
        "critical-text": "#7F1D1D",
        strategic: "#5B21B6",
        "strategic-bg": "#EDE9FE",
        "strategic-bg-2": "#C4B5FD",
        "strategic-text": "#4C1D95",
        high: "#854D0E",
        "high-bg": "#FEF7E0",
        "high-bg-2": "#FBE197",
        "high-text": "#713F12",
        med: "#334155",
        "med-bg": "#E2E8F0",
        "med-bg-2": "#CBD5E1",
        "med-text": "#1E293B",
      },
      fontFamily: {
        serif: ["Newsreader", "Georgia", "serif"],
        sans: ["Inter", "system-ui", "-apple-system", "sans-serif"],
        mono: ["JetBrains Mono", "ui-monospace", "monospace"],
      },
      borderRadius: {
        sm: "4px",
        DEFAULT: "6px",
        md: "6px",
        lg: "8px",
        xl: "10px",
        "2xl": "14px",
      },
      transitionTimingFunction: {
        out: "cubic-bezier(0.16, 1, 0.3, 1)",
        "out-soft": "cubic-bezier(0.22, 0.61, 0.36, 1)",
        spring: "cubic-bezier(0.34, 1.56, 0.64, 1)",
        organic: "cubic-bezier(0.4, 0, 0.6, 1)",
      },
    },
  },
  plugins: [],
};
